name: prod
root: /Users/andreasbade/repos/fb-provisioning
attach: false
post: tmux -CC attach

windows:
  - production logs:
      layout: tiled
      panes:
        - prod 1 less:
          - cd .
          - ./fb-cloud connect prod 1
          - less -R +F /var/log/wildfly/console.log
        - prod 1 htop:
          - cd .
          - ./fb-cloud connect prod 1
          - htop
        - prod 2 less:
          - cd .
          - ./fb-cloud connect prod 2
          - less -R +F /var/log/wildfly/console.log
        - prod 2 htop:
          - cd .
          - ./fb-cloud connect prod 2
          - htop
